# Generated by Django 4.2.16 on 2024-12-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='number',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='学号'),
        ),
    ]
