# Generated by Django 4.2.16 on 2024-12-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0003_customuser_is_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to='submissions/'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to='submissions/'),
        ),
    ]
