# Generated by Django 4.2.16 on 2025-01-01 12:47

import assignment_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0004_alter_submission_file_alter_submission_html_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='file',
            field=models.FileField(upload_to=assignment_system.models.get_upload_path),
        ),
        migrations.AlterField(
            model_name='submission',
            name='html_file',
            field=models.FileField(blank=True, null=True, upload_to=assignment_system.models.get_upload_path),
        ),
    ]
