# Generated by Django 4.2.16 on 2025-01-02 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0009_alter_scores_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='score',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='成绩'),
        ),
        migrations.AlterField(
            model_name='scores',
            name='submission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='assignment_system.submission'),
        ),
    ]
