# Generated by Django 4.2.16 on 2025-01-02 12:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0010_alter_scores_score_alter_scores_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scores',
            name='submission',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='score', to='assignment_system.submission'),
        ),
    ]
