# Generated by Django 4.2.16 on 2025-01-31 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0011_alter_scores_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentsubmissionstatus',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='assignment_system.assignment', verbose_name='作业'),
        ),
    ]
