# Generated by Django 4.2.16 on 2025-02-01 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0012_alter_studentsubmissionstatus_question'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentSubmissionStatus',
        ),
    ]
