# Generated by Django 4.2.16 on 2025-02-01 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0013_delete_studentsubmissionstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='creat_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
