# Generated by Django 4.2.16 on 2025-02-02 15:33

import assignment_system.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0014_submission_creat_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=assignment_system.models.get_upload_path),
        ),
    ]
