# Generated by Django 4.2.16 on 2025-12-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0018_alter_submission_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='custom_answers',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
