# Generated by Django 4.2.16 on 2025-12-27 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment_system', '0019_submission_custom_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='custom_fields',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
